// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026  Pierre Jacquel
//
// This file is part of milton-browser-extension.
// See COPYING for license terms.

// Translator bundle — returns translators bundled at build time (BE-8-4).
// For BE-8-4 the bundle contains one entry (arXiv) used by the integration
// spike. BE-8-5 expands the bundle to the curated subset (~100 publishers)
// via a build-time pipeline; BE-8-5 also lands the CDN-fetch long-tail
// fallback that BE-8-4 originally planned (translator-fetcher.ts, deferred).
//
// Translator metadata header parsing: Zotero translator files start with a
// JSON-ish block followed by JS code. Header is parsed once on import;
// metadata is cached in-memory for the lifetime of the sandbox page.

import type { BundledTranslator, TranslatorMetadata } from './zotero-types'
import pin from '../../translator-bundle-pin.json' with { type: 'json' }
import { bytesToHex } from './manifest-verify'

interface BundleEntry {
  source: string
  parsed?: BundledTranslator
}

interface ParsedHeader {
  metadata: TranslatorMetadata
  bodyStart: number
}

function parseTranslatorHeader(source: string): ParsedHeader {
  // Header is the first balanced `{ ... }` block. Skip leading whitespace,
  // `//` line comments, and `/* ... */` block comments (the vendoring header
  // we prepend at Task 6, plus any upstream-style leading prologue).
  // Find via brace counting; string literals (",  ', `) may contain braces.
  let i = 0
  while (i < source.length) {
    const c = source[i]
    if (/\s/.test(c)) {
      i++
      continue
    }
    if (c === '/' && source[i + 1] === '/') {
      while (i < source.length && source[i] !== '\n') i++
      continue
    }
    if (c === '/' && source[i + 1] === '*') {
      i += 2
      while (i < source.length && !(source[i] === '*' && source[i + 1] === '/')) i++
      i += 2 // skip closing */
      continue
    }
    break
  }
  if (source[i] !== '{') {
    throw new TranslatorMalformedError('header does not start with { after skipping comments + whitespace')
  }
  let depth = 0
  let end = -1
  for (let j = i; j < source.length; j++) {
    const c = source[j]
    if (c === '"' || c === "'" || c === '`') {
      // Skip string / template literal. We don't attempt to handle template
      // interpolations (`${ ... }`) — Zotero translator metadata blocks are
      // strict JSON so they don't contain them; if a future translator does,
      // this parser would need to be replaced with a real JS tokenizer.
      const quote = c
      j++
      while (j < source.length && source[j] !== quote) {
        if (source[j] === '\\') j++
        j++
      }
      continue
    }
    if (c === '{') depth++
    else if (c === '}') {
      depth--
      if (depth === 0) {
        end = j + 1
        break
      }
    }
  }
  if (end === -1) {
    throw new TranslatorMalformedError('unbalanced braces in header')
  }
  const headerStr = source.slice(i, end)
  let metadata: TranslatorMetadata
  try {
    metadata = JSON.parse(headerStr) as TranslatorMetadata
  } catch (err) {
    throw new TranslatorMalformedError(`header JSON parse failed: ${String(err)}`)
  }
  if (typeof metadata.translatorID !== 'string' || metadata.translatorID.length === 0) {
    throw new TranslatorMalformedError('missing translatorID in header')
  }
  return { metadata, bodyStart: end }
}

export class TranslatorMalformedError extends Error {
  constructor(reason: string) {
    super(`Translator malformed: ${reason}`)
    this.name = 'TranslatorMalformedError'
  }
}

// Build-time registry: each entry sourced via Vite ?raw import.
// REGISTRY block is auto-generated by scripts/refresh-translator-bundle.ts.
// Re-run via `pnpm refresh:translators` after curating
// src/translator-runtime/curated-translators.txt.
// GENERATED-START — populated by scripts/refresh-translator-bundle.ts; do NOT hand-edit
import acmDigitalLibrarySource from './translators/acm-digital-library.js?raw'
import arxivOrgSource from './translators/arxiv-org.js?raw'
import atyponJournalsSource from './translators/atypon-journals.js?raw'
import cambridgeCoreSource from './translators/cambridge-core.js?raw'
import cellPressSource from './translators/cell-press.js?raw'
import coinsSource from './translators/coins.js?raw'
import doiContentNegotiationSource from './translators/doi-content-negotiation.js?raw'
import embeddedMetadataSource from './translators/embedded-metadata.js?raw'
import highwireSource from './translators/highwire.js?raw'
import highwire20Source from './translators/highwire-2-0.js?raw'
import ieeeXploreSource from './translators/ieee-xplore.js?raw'
import jstorSource from './translators/jstor.js?raw'
import nationalBureauOfEconomicResearchSource from './translators/national-bureau-of-economic-research.js?raw'
import naturePublishingGroupSource from './translators/nature-publishing-group.js?raw'
import oxfordUniversityPressSource from './translators/oxford-university-press.js?raw'
import projectMuseSource from './translators/project-muse.js?raw'
import pubmedSource from './translators/pubmed.js?raw'
import pubmedCentralSource from './translators/pubmed-central.js?raw'
import repecIdeasSource from './translators/repec-ideas.js?raw'
import sageJournalsSource from './translators/sage-journals.js?raw'
import sciencedirectSource from './translators/sciencedirect.js?raw'
import springerLinkSource from './translators/springer-link.js?raw'
import ssrnSource from './translators/ssrn.js?raw'
import taylorAndFrancisNejmSource from './translators/taylor-and-francis-nejm.js?raw'
import unapiSource from './translators/unapi.js?raw'
import wileyOnlineLibrarySource from './translators/wiley-online-library.js?raw'

const REGISTRY: Record<string, BundleEntry> = {
  "acm-digital-library": { source: acmDigitalLibrarySource },
  "arxiv-org": { source: arxivOrgSource },
  "atypon-journals": { source: atyponJournalsSource },
  "cambridge-core": { source: cambridgeCoreSource },
  "cell-press": { source: cellPressSource },
  "coins": { source: coinsSource },
  "doi-content-negotiation": { source: doiContentNegotiationSource },
  "embedded-metadata": { source: embeddedMetadataSource },
  "highwire": { source: highwireSource },
  "highwire-2-0": { source: highwire20Source },
  "ieee-xplore": { source: ieeeXploreSource },
  "jstor": { source: jstorSource },
  "national-bureau-of-economic-research": { source: nationalBureauOfEconomicResearchSource },
  "nature-publishing-group": { source: naturePublishingGroupSource },
  "oxford-university-press": { source: oxfordUniversityPressSource },
  "project-muse": { source: projectMuseSource },
  "pubmed": { source: pubmedSource },
  "pubmed-central": { source: pubmedCentralSource },
  "repec-ideas": { source: repecIdeasSource },
  "sage-journals": { source: sageJournalsSource },
  "sciencedirect": { source: sciencedirectSource },
  "springer-link": { source: springerLinkSource },
  "ssrn": { source: ssrnSource },
  "taylor-and-francis-nejm": { source: taylorAndFrancisNejmSource },
  "unapi": { source: unapiSource },
  "wiley-online-library": { source: wileyOnlineLibrarySource },
}
// GENERATED-END

let idIndex: Map<string, string> | null = null

function buildIdIndex(): Map<string, string> {
  const idx = new Map<string, string>()
  for (const [key, entry] of Object.entries(REGISTRY)) {
    const { metadata } = parseTranslatorHeader(entry.source)
    // Body is the FULL translator source (incl. metadata object literal +
    // license block + function declarations). The framework evals
    //   `var ZOTERO_TRANSLATOR_INFO = ${body}`
    // which requires the metadata block to BE the value, then the function
    // declarations follow as top-level statements (ASI inserts `;` after
    // the closing `}` of the object literal). Stripping the metadata
    // block — as the original implementation did — leaves an invalid
    // `var ZOTERO_TRANSLATOR_INFO = function ...` parse error.
    entry.parsed = { metadata, body: entry.source }
    idx.set(metadata.translatorID, key)
  }
  return idx
}

// Bundle integrity check (AC6). Verified ONCE at sandbox bootstrap via
// verifyAllBundleIntegrity(); subsequent getBundledTranslator() calls
// consult `verifiedSet` for an O(1) gate. Pre-verifying at bootstrap
// avoids both (a) making getBundledTranslator async — which would force
// runTranslation through a sync→async refactor — and (b) a race condition
// where two concurrent first-calls both compute the digest.
//
// If bootstrap hasn't run yet (verifiedSet === null), getBundledTranslator
// returns null defensively — the lazy CDN-fetch path (translator-fetcher.ts
// in Task 5) takes over. This is the intended graceful-degradation flow.
let verifiedSet: Set<string> | null = null

/**
 * Verify every REGISTRY entry's SHA-256 hash against the build-time pin
 * (translator-bundle-pin.json). Returns the set of translatorIDs that
 * verified successfully — the caller (sandbox bootstrap) should then call
 * `_setVerifiedSet(set)` to install it. UUIDs whose source bytes have been
 * tampered with (or whose hash is simply missing from the pin) are NOT
 * included in the returned set; subsequent getBundledTranslator(uuid)
 * calls return null for them, and lazy CDN-fetch is the recovery path.
 *
 * Logged on failure with the failing UUID + expected-vs-actual hex hashes
 * so a tamper signal is visible in DevTools.
 */
export async function verifyAllBundleIntegrity(): Promise<Set<string>> {
  if (idIndex === null) {
    idIndex = buildIdIndex()
  }
  const verified = new Set<string>()
  const encoder = new TextEncoder()
  for (const [, key] of [...idIndex.entries()]) {
    const entry = REGISTRY[key]
    const parsed = entry.parsed
    if (parsed === undefined) continue // buildIdIndex always populates parsed; defensive
    const translatorID = parsed.metadata.translatorID
    const expectedHex = (pin.bundleHashes as Record<string, string>)[translatorID]
    if (expectedHex === undefined) {
      console.warn(
        `[translator-bundle] no pin entry for ${translatorID} (${parsed.metadata.label}); skipping`,
      )
      continue
    }
    const digestBuf = await crypto.subtle.digest('SHA-256', encoder.encode(entry.source))
    const actualHex = bytesToHex(new Uint8Array(digestBuf))
    if (actualHex !== expectedHex) {
      console.warn(
        `[translator-bundle] integrity mismatch for ${translatorID} (${parsed.metadata.label}):\n` +
          `  expected: ${expectedHex}\n` +
          `  actual:   ${actualHex}`,
      )
      continue
    }
    verified.add(translatorID)
  }
  return verified
}

/**
 * Install the verified set. Called by sandbox.ts bootstrap with the result
 * of verifyAllBundleIntegrity(). Subsequent getBundledTranslator() calls
 * then gate on this set. Idempotent — re-calling with a larger set
 * (additional UUIDs verified) is safe; shrinking the set would surface as
 * silently-disappearing translators and is intentionally allowed for tests
 * (via the test seam below).
 */
export function _setVerifiedSet(set: Set<string>): void {
  verifiedSet = set
}

/**
 * Test seam: reset the verified set + lazy index. Called by tests that
 * mutate REGISTRY or want to exercise the unbootstrapped state.
 */
export function _resetForTests(): void {
  verifiedSet = null
  idIndex = null
}

export function getBundledTranslator(translatorID: string): BundledTranslator | null {
  if (idIndex === null) {
    idIndex = buildIdIndex()
  }
  // Gate on the verified set — if bootstrap hasn't installed it yet, OR if
  // this UUID failed integrity verification, return null. Caller's lazy
  // CDN-fetch path is the recovery.
  if (verifiedSet === null) return null
  if (!verifiedSet.has(translatorID)) return null
  const key = idIndex.get(translatorID)
  if (key === undefined) return null
  const entry = REGISTRY[key]
  return entry.parsed ?? null
}

export function listBundledTranslatorIDs(): string[] {
  if (idIndex === null) {
    idIndex = buildIdIndex()
  }
  return [...idIndex.keys()]
}

/**
 * BE-8-6: return parsed metadata for every bundled entry. Consumed by the
 * translator-router (URL → UUID discovery) so it can match `metadata.target`
 * regexes against the active tab URL without going through the sandbox's
 * registry (the popup runs in a different window from the sandbox).
 *
 * Returns ALL bundled entries regardless of `verifiedSet` state — discovery
 * needs to see candidate UUIDs even pre-bootstrap; the verifiedSet gate
 * applies later when `getBundledTranslator(uuid)` is actually called.
 */
export function listBundledTranslators(): BundledTranslator[] {
  if (idIndex === null) {
    idIndex = buildIdIndex()
  }
  const out: BundledTranslator[] = []
  for (const key of idIndex.values()) {
    const parsed = REGISTRY[key].parsed
    if (parsed !== undefined) out.push(parsed)
  }
  return out
}

// Test seam: reset the lazy index (called by tests that mutate REGISTRY).
// Kept for backward compat with BE-8-4 tests; new tests prefer _resetForTests.
export function _resetIdIndexForTests(): void {
  idIndex = null
}
