// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026  Pierre Jacquel
//
// This file is part of milton-browser-extension.
// See COPYING for license terms.

// Translator bundle — returns translators bundled at build time (BE-8-4).
// For BE-8-4 the bundle contains one entry (arXiv) used by the integration
// spike. BE-8-5 expands the bundle to the curated subset (~100 publishers)
// via a build-time pipeline; BE-8-5 also lands the CDN-fetch long-tail
// fallback that BE-8-4 originally planned (translator-fetcher.ts, deferred).
//
// Translator metadata header parsing: Zotero translator files start with a
// JSON-ish block followed by JS code. Header is parsed once on import;
// metadata is cached in-memory for the lifetime of the sandbox page.

import type { BundledTranslator, TranslatorMetadata } from './zotero-types'

interface BundleEntry {
  source: string
  parsed?: BundledTranslator
}

interface ParsedHeader {
  metadata: TranslatorMetadata
  bodyStart: number
}

function parseTranslatorHeader(source: string): ParsedHeader {
  // Header is the first balanced `{ ... }` block. Skip leading whitespace,
  // `//` line comments, and `/* ... */` block comments (the vendoring header
  // we prepend at Task 6, plus any upstream-style leading prologue).
  // Find via brace counting; string literals (",  ', `) may contain braces.
  let i = 0
  while (i < source.length) {
    const c = source[i]
    if (/\s/.test(c)) {
      i++
      continue
    }
    if (c === '/' && source[i + 1] === '/') {
      while (i < source.length && source[i] !== '\n') i++
      continue
    }
    if (c === '/' && source[i + 1] === '*') {
      i += 2
      while (i < source.length && !(source[i] === '*' && source[i + 1] === '/')) i++
      i += 2 // skip closing */
      continue
    }
    break
  }
  if (source[i] !== '{') {
    throw new TranslatorMalformedError('header does not start with { after skipping comments + whitespace')
  }
  let depth = 0
  let end = -1
  for (let j = i; j < source.length; j++) {
    const c = source[j]
    if (c === '"' || c === "'" || c === '`') {
      // Skip string / template literal. We don't attempt to handle template
      // interpolations (`${ ... }`) — Zotero translator metadata blocks are
      // strict JSON so they don't contain them; if a future translator does,
      // this parser would need to be replaced with a real JS tokenizer.
      const quote = c
      j++
      while (j < source.length && source[j] !== quote) {
        if (source[j] === '\\') j++
        j++
      }
      continue
    }
    if (c === '{') depth++
    else if (c === '}') {
      depth--
      if (depth === 0) {
        end = j + 1
        break
      }
    }
  }
  if (end === -1) {
    throw new TranslatorMalformedError('unbalanced braces in header')
  }
  const headerStr = source.slice(i, end)
  let metadata: TranslatorMetadata
  try {
    metadata = JSON.parse(headerStr) as TranslatorMetadata
  } catch (err) {
    throw new TranslatorMalformedError(`header JSON parse failed: ${String(err)}`)
  }
  if (typeof metadata.translatorID !== 'string' || metadata.translatorID.length === 0) {
    throw new TranslatorMalformedError('missing translatorID in header')
  }
  return { metadata, bodyStart: end }
}

export class TranslatorMalformedError extends Error {
  constructor(reason: string) {
    super(`Translator malformed: ${reason}`)
    this.name = 'TranslatorMalformedError'
  }
}

// Build-time registry: each entry sourced via Vite ?raw import.
// REGISTRY block is auto-generated by scripts/refresh-translator-bundle.ts.
// Re-run via `pnpm refresh:translators` after curating
// src/translator-runtime/curated-translators.txt.
// GENERATED-START — populated by scripts/refresh-translator-bundle.ts; do NOT hand-edit
import acmDigitalLibrarySource from './translators/acm-digital-library.js?raw'
import arxivOrgSource from './translators/arxiv-org.js?raw'
import atyponJournalsSource from './translators/atypon-journals.js?raw'
import cambridgeCoreSource from './translators/cambridge-core.js?raw'
import cellPressSource from './translators/cell-press.js?raw'
import coinsSource from './translators/coins.js?raw'
import doiContentNegotiationSource from './translators/doi-content-negotiation.js?raw'
import embeddedMetadataSource from './translators/embedded-metadata.js?raw'
import highwireSource from './translators/highwire.js?raw'
import highwire20Source from './translators/highwire-2-0.js?raw'
import ieeeXploreSource from './translators/ieee-xplore.js?raw'
import jstorSource from './translators/jstor.js?raw'
import nationalBureauOfEconomicResearchSource from './translators/national-bureau-of-economic-research.js?raw'
import naturePublishingGroupSource from './translators/nature-publishing-group.js?raw'
import oxfordUniversityPressSource from './translators/oxford-university-press.js?raw'
import projectMuseSource from './translators/project-muse.js?raw'
import pubmedSource from './translators/pubmed.js?raw'
import pubmedCentralSource from './translators/pubmed-central.js?raw'
import repecIdeasSource from './translators/repec-ideas.js?raw'
import sageJournalsSource from './translators/sage-journals.js?raw'
import sciencedirectSource from './translators/sciencedirect.js?raw'
import springerLinkSource from './translators/springer-link.js?raw'
import ssrnSource from './translators/ssrn.js?raw'
import taylorAndFrancisNejmSource from './translators/taylor-and-francis-nejm.js?raw'
import unapiSource from './translators/unapi.js?raw'
import wileyOnlineLibrarySource from './translators/wiley-online-library.js?raw'

const REGISTRY: Record<string, BundleEntry> = {
  "acm-digital-library": { source: acmDigitalLibrarySource },
  "arxiv-org": { source: arxivOrgSource },
  "atypon-journals": { source: atyponJournalsSource },
  "cambridge-core": { source: cambridgeCoreSource },
  "cell-press": { source: cellPressSource },
  "coins": { source: coinsSource },
  "doi-content-negotiation": { source: doiContentNegotiationSource },
  "embedded-metadata": { source: embeddedMetadataSource },
  "highwire": { source: highwireSource },
  "highwire-2-0": { source: highwire20Source },
  "ieee-xplore": { source: ieeeXploreSource },
  "jstor": { source: jstorSource },
  "national-bureau-of-economic-research": { source: nationalBureauOfEconomicResearchSource },
  "nature-publishing-group": { source: naturePublishingGroupSource },
  "oxford-university-press": { source: oxfordUniversityPressSource },
  "project-muse": { source: projectMuseSource },
  "pubmed": { source: pubmedSource },
  "pubmed-central": { source: pubmedCentralSource },
  "repec-ideas": { source: repecIdeasSource },
  "sage-journals": { source: sageJournalsSource },
  "sciencedirect": { source: sciencedirectSource },
  "springer-link": { source: springerLinkSource },
  "ssrn": { source: ssrnSource },
  "taylor-and-francis-nejm": { source: taylorAndFrancisNejmSource },
  "unapi": { source: unapiSource },
  "wiley-online-library": { source: wileyOnlineLibrarySource },
}
// GENERATED-END

let idIndex: Map<string, string> | null = null

function buildIdIndex(): Map<string, string> {
  const idx = new Map<string, string>()
  for (const [key, entry] of Object.entries(REGISTRY)) {
    const { metadata } = parseTranslatorHeader(entry.source)
    // Body is the FULL translator source (incl. metadata object literal +
    // license block + function declarations). The framework evals
    //   `var ZOTERO_TRANSLATOR_INFO = ${body}`
    // which requires the metadata block to BE the value, then the function
    // declarations follow as top-level statements (ASI inserts `;` after
    // the closing `}` of the object literal). Stripping the metadata
    // block — as the original implementation did — leaves an invalid
    // `var ZOTERO_TRANSLATOR_INFO = function ...` parse error.
    entry.parsed = { metadata, body: entry.source }
    idx.set(metadata.translatorID, key)
  }
  return idx
}

export function getBundledTranslator(translatorID: string): BundledTranslator | null {
  if (idIndex === null) {
    idIndex = buildIdIndex()
  }
  const key = idIndex.get(translatorID)
  if (key === undefined) return null
  const entry = REGISTRY[key]
  return entry.parsed ?? null
}

export function listBundledTranslatorIDs(): string[] {
  if (idIndex === null) {
    idIndex = buildIdIndex()
  }
  return [...idIndex.keys()]
}

// Test seam: reset the lazy index (called by tests that mutate REGISTRY).
export function _resetIdIndexForTests(): void {
  idIndex = null
}
